[package]
name = "backend-frigate"
version = "0.1.0"
edition = "2024"
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
spdk-core.workspace = true

electrum_streaming_client.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
bitcoin.workspace = true
futures.workspace = true
anyhow.workspace = true
async-trait.workspace = true

